### PR TITLE
comma removed

### PR DESCRIPTION
**Pull request by gluk64**
your app.json is broken and won't deploy to heroku. here's a fix.

### CODE REVIEW

**Comment by lfilho** [comment]
Thanks man! But your PR does more than it says!

Please remove the extra commits so I can merge it.

**Comment by gluk64** [comment]
The rest of the commits are important too: they add information to the messages about the PR author. Otherwise the whole team has to click on each PR link in slack to check, whether they are concerned or not.

If you don't wanna merge it, just remove the comma manually, it's one symbol only.

**Comment by lfilho** [comment]
1- [Separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns). Even while contributing to open source :wink: Different needs, different proposals, different discussions, different votes, different PRs. No worries, I'll remove the extra comma myself then. Thanks for pointing it out again.

2- I couldn't accept your PR either way: it's breaking the build. Those changes should have come with the appropriate tests as well. If you want then, please contribute with the tests as well.

PS: By the time I wrote this repo, BitBucket didn't provide those infos in their payload. Finally they do! Cool!

**Comment by lfilho** [comment]
There ya go: https://github.com/lfilho/bitbucket-slack-pr-hook/commit/f5d187e23b6f73a0da58681c29621624c87849db

**Comment by gluk64** [comment]
I see and agree. I only created the first pool request actually, it updated automatically with the new commits.

Would love to contribute to the tests, but I got my own release burning ;)

**Pull request closed without merging**
