### PR TITLE
Mention reviewers when create a new PR

### PR DESCRIPTION
**Pull request by gbmoretti**
As discussed in #13 now you can set `MENTION_REVIEWERS` environment variable to notify reviewers in Slack.

This feature is disabled by default.

### CODE REVIEW

**Comment by gbmoretti** [comment]
Just pinging @lfilho 

Any thoughts about this?

**Comment by lfilho** [comment]
Sorry, man. For some reason I didn't get the first notification (or went overlooked). Reviewing it right now!

**Comment by lfilho** [comment]
Looks fine to me! Thanks, @gbmoretti

**Comment by spawn-guy** [comment]
maybe some improvements? like... a database with slack-team-nickname to bitbucket-user matching.
'cause in this situation you Have to have same usernames both in bitb and slack

**Pull request merged**
