### PR TITLE
Update for Slack API, quick Heroku Deploy, and Changeable Hex Colors

### PR DESCRIPTION
**Pull request by brh55**
- Add some new optional environmental variable configs
- Reconfigure node-slack to work with new Slack API
- Set up template and add quick deploy Heroku badge
- Updated readme to reflect changes

### CODE REVIEW

**Comment by quaninte** [comment]
@lfilho can you merge this? I can't set this up since Slack changed their integrations page

**Comment by brh55** [comment]
This resolves people who have set up their repo hooks before the bitbucket update. However with the new schema, you might experience unintended or broken behavior 😓…

**Comment by quaninte** [comment]
@brh55 any idea how to set this up correctly? I tried your repo but it doesn't work either?
Maybe you can spend sometime to fix it?

**Comment by lfilho** [comment]
Hey guys, sorry for the long delay! I must have overlooked the notification email!!

So, I quit using BitBucket in favor of GitHub (many reasons), so I wasn't actively developing this anymore. I'm happy to merge if anyone could confirm this works / solves the problem.

**Comment by brh55** [comment]
@lfilho - This resolves issues to older repositories regards to node-slack updates.
However, anyone setting up a new repository, this fix won't apply. I'll see if I can submit another PR updating the parser.

**Comment by lfilho** [comment]
Perfect, thanks again!

**Comment by brh55** [comment]
@quaninte

I did fix the issue, but I need to spend a hour or two updating the unit test before I can finalize this PR. 
If you need it ASAP you can build off my existing forked dev branch.

**Comment by quaninte** [comment]
@brh55 Thank you very much, it is working now, but there're some problems with branch names

image

**Comment by brh55** [comment]
@lfilho @quaninte 

Updated PR, everything should be fully functional now. Might be worth updating the release version to indicate it's for the new bitbucket schema. :dart:

**Comment by quaninte** [comment]
@brh55 Sweet! all is working fine now, thanks again.
@lfilho :+1: to merge this

**Comment by lfilho** [comment]
Awesome, guys! Will do!
Thanks for all the contributions!

**Pull request merged**
